In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, recall_score, f1_score, multilabel_confusion_matrix
from imblearn.metrics import geometric_mean_score, specificity_score
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import VotingClassifier
import json
import pandas as pd
import numpy as np
import sys, os
import warnings
import datetime
#import pickle
from joblib import dump, load
from pathlib import Path

from sklearn import metrics
from sklearn.metrics import classification_report

from art.attacks.evasion import FastGradientMethod, DecisionTreeAttack, ZooAttack
from art.estimators.classification import SklearnClassifier
from art.estimators.classification.scikitlearn import ScikitlearnDecisionTreeClassifier

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/art/estimators/certification/__init__.py:28: UserWarning: PyTorch not found. Not importing DeepZ or Interval Bound Propagation functionality
  warnings.warn("PyTorch not found. Not importing DeepZ or Interval Bound Propagation functionality")


In [3]:


XCols = ['mean', 'sum', 'std']
label = 'label'



In [4]:
#df = pd.read_csv(sys.argv[1], dtype = fieldTypes, parse_dates = ['time_start'])
df = pd.read_csv("/rds/general/user/as9820/home/revist/revisiting-iot-device-identification/data/stats_nov_apr.csv", parse_dates = ['time'])
df.fillna(0, inplace=True)

weeks = [list(range(44,53)), list(range(1,10)), list(range(10,19))]




In [5]:
# trainCon = df['time'] >= pd.Timestamp('2020-03-01')
#trainCon = df['time'] < pd.Timestamp('2020-01-01')
#trainCon = ((df['time'] >= pd.Timestamp('2020-01-01')) & (df['time'] < pd.Timestamp('2020-03-01')))
trainCon = df['time'].dt.isocalendar().week.isin(weeks[0])
#trainCon = df['time'].dt.week.isin([44,45])


#testCon = df['time'] > pd.Timestamp('2020-02-29')
#testCons = pd.date_range('2019-11-01', '2020-05-01', freq = '1W').tolist()
testCons = pd.date_range('2019-11-01', '2020-05-01', freq = '1W').tolist()
#testCons = pd.date_range('2019-11-01', '2019-12-01', freq = '1W').tolist()

#X = dfTrain.iloc[:, 2:5]
#y = dfTrain.iloc[:, 1]
X = df[trainCon][XCols]
y = df[trainCon][label]

In [6]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)


In [7]:
#clf = RandomForestClassifier(n_estimators=20, n_jobs=50)
#rfc = RandomForestClassifier(n_jobs=18)
#svc = SVC(verbose=True)
dtc = DecisionTreeClassifier()
#knn = KNeighborsClassifier(n_jobs=54)
#mv = VotingClassifier(estimators=[('knn', knn), ('dt', dtc), ('rf', rfc), ('svm',svc)], voting='hard', n_jobs=54)

modelFile = Path(f"model/dtc_0_1sec")
if modelFile.is_file():
    print(f"loading model {modelFile}")
    dtc = load(modelFile)
else:
    print(f"start training for weeks {weeks[2]}")
    dtc.fit(X_train.values, y_train)
    print("DTC trained")
    #dump(rfc, f"model/rfc_{sys.argv[2]}")
    dump(dtc, modelFile)


loading model model/dtc_0_1sec


In [21]:
for date in testCons:
    testCon = df['time'].dt.isocalendar().week == pd.Timestamp(date).week
    #testCon = df['time'].dt.date == pd.Timestamp(date).date
    testDF = df[testCon]

    X = testDF[XCols]
    y = testDF[label]
    
    if len(X) == 0: 
        continue
    
    #y_pred = clf.predict(X)
    #y_rfc = rfc.predict(X)
    #print("rfc predict")
    #y_svc = svc.predict(X)
    #print("svc predict")
    y_dtc = dtc.predict(X)
    #print("dtc predict")
    #y_knn = knn.predict(X)
    #print("knn predict")
    #y_mv = mv.predict(X)
    #print("mv predict")
    
    print(f"{date.week}", metrics.f1_score(y, y_dtc, average='micro'))
    print(classification_report(y,y_dtc))#, labels=devs))

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


44 0.716661276583152


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

              precision    recall  f1-score   support

           7       0.83      0.49      0.62      6745
           8       0.51      0.91      0.65     36559
           9       0.36      0.02      0.04      9418
          10       0.90      0.91      0.91     12953
          12       0.83      0.38      0.52      7509
          14       0.84      0.82      0.83     11626
          15       0.63      0.50      0.56     23081
          16       0.53      0.49      0.51     66903
          17       0.00      0.00      0.00         0
          18       0.90      0.97      0.93     66743
          19       0.61      0.07      0.12     36295
          20       0.69      0.60      0.64       944
          22       0.87      1.00      0.93     81312
          23       0.51      0.50      0.50      4289
          24       0.72      0.19      0.31     11994
          25       0.84      0.99      0.91     16473
          27       0.98      0.33      0.49      5368
          28       0.47    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


45 0.7222273215490574
              precision    recall  f1-score   support

           7       0.98      0.61      0.75    142115
           8       0.50      0.88      0.64    144668
           9       0.71      0.28      0.40     45241
          10       0.87      0.90      0.89     52818
          12       0.66      0.92      0.77    148710
          14       0.74      0.78      0.76     43272
          15       0.72      0.72      0.72    109634
          16       0.49      0.50      0.50    248788
          17       0.93      0.62      0.74     14544
          18       0.88      0.97      0.92    257285
          19       0.54      0.09      0.16    146426
          20       0.23      0.45      0.30      4327
          22       0.70      0.96      0.81    212008
          23       0.70      0.73      0.72     23682
          24       0.71      0.17      0.27     51543
          25       0.81      0.99      0.89     87895
          27       0.97      0.27      0.42    115848
     

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


46 0.7405074974081473
              precision    recall  f1-score   support

           7       0.86      0.49      0.62     23908
           8       0.50      0.93      0.65    133305
           9       0.94      0.52      0.67     43781
          10       0.92      0.90      0.91     43927
          12       0.84      0.47      0.60     30254
          14       0.79      0.79      0.79     43880
          15       0.54      0.70      0.61     66008
          16       0.63      0.50      0.55    447899
          17       0.95      0.52      0.67     15588
          18       0.97      0.97      0.97    234606
          19       0.41      0.01      0.02    133445
          20       0.60      0.59      0.59      3692
          22       0.91      1.00      0.95    345014
          23       0.29      0.33      0.31      9006
          24       0.56      0.18      0.28     40932
          25       0.76      0.98      0.85     34610
          27       0.99      0.50      0.66     25696
     

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


47 0.7219468409816687
              precision    recall  f1-score   support

           7       0.86      0.49      0.62     23434
           8       0.51      0.90      0.65    125743
           9       0.46      0.46      0.46     44372
          10       0.93      0.92      0.92     47172
          12       0.84      0.46      0.59     26405
          14       0.78      0.80      0.79     41118
          15       0.47      0.70      0.56     65078
          16       0.59      0.55      0.57    412871
          17       0.96      0.57      0.72     16085
          18       0.96      0.97      0.96    222083
          19       0.51      0.08      0.13    124628
          20       0.54      0.59      0.56      3868
          22       0.90      1.00      0.95    336185
          23       0.53      0.15      0.24     51609
          24       0.38      0.12      0.18     43408
          25       0.52      0.96      0.67     16264
          27       0.98      0.50      0.66     23901
     

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


48 0.7772535867571513
              precision    recall  f1-score   support

           7       0.91      0.50      0.64     37178
           8       0.50      0.88      0.64    199285
           9       0.67      0.42      0.52     63841
          10       0.99      0.71      0.83     55480
          12       0.85      0.48      0.61     47948
          14       0.78      0.78      0.78     57633
          15       0.53      0.70      0.60    104629
          16       0.66      0.75      0.70    633618
          17       0.97      0.48      0.64     21328
          18       0.97      0.97      0.97    366565
          19       0.51      0.08      0.13    199374
          20       0.94      0.60      0.73      5790
          22       0.90      1.00      0.95    459505
          23       0.46      0.50      0.48     22620
          24       0.80      0.29      0.42     84680
          25       0.59      0.96      0.73     26269
          27       1.00      0.51      0.68     39495
     

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


49 0.7880289712843981
              precision    recall  f1-score   support

           7       0.91      0.49      0.63     41723
           8       0.50      0.88      0.64    220605
           9       0.80      0.52      0.63     75860
          10       0.99      0.79      0.88     69738
          12       0.85      0.49      0.62     54084
          14       0.80      0.79      0.79     64200
          15       0.54      0.70      0.61    115643
          16       0.68      0.72      0.70    717815
          17       0.95      0.47      0.63     24382
          18       0.97      0.96      0.97    404703
          19       0.50      0.08      0.13    220202
          20       0.94      0.61      0.74      6236
          22       0.92      1.00      0.96    597306
          23       0.47      0.52      0.49     24102
          24       0.76      0.28      0.41     88537
          25       0.60      0.96      0.74     29017
          27       1.00      0.51      0.67     44573
     

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


50 0.8079522039228022
              precision    recall  f1-score   support

           7       0.86      0.39      0.54     51922
           8       0.50      0.89      0.64    220678
           9       0.77      0.50      0.61     78084
          10       0.96      0.91      0.93     82924
          12       0.87      0.50      0.63     54370
          14       0.85      0.88      0.87     71599
          15       0.48      0.70      0.57    114745
          16       0.74      0.82      0.78    680528
          17       0.96      0.46      0.62     24923
          18       0.97      0.97      0.97    407324
          19       0.50      0.07      0.13    220412
          20       0.72      0.61      0.66      6365
          22       0.91      1.00      0.95    514873
          23       0.47      0.52      0.50     24005
          24       0.72      0.24      0.36     87369
          25       0.57      0.96      0.72     26667
          27       1.00      0.52      0.68     44308
     

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


51 0.7773954778584209
              precision    recall  f1-score   support

           7       0.84      0.29      0.43     70703
           8       0.51      0.90      0.65    222659
           9       0.76      0.28      0.41     70055
          10       0.93      0.92      0.93     90462
          12       0.86      0.48      0.62     51839
          14       0.83      0.84      0.83     74136
          15       0.47      0.69      0.56    113259
          16       0.69      0.71      0.70    702270
          17       0.96      0.46      0.62     25408
          18       0.97      0.97      0.97    407994
          19       0.54      0.07      0.13    220987
          20       0.71      0.59      0.64      6414
          22       0.88      1.00      0.94    596713
          23       0.51      0.51      0.51     24841
          24       0.60      0.15      0.24     75712
          25       0.57      0.96      0.71     26462
          27       0.99      0.51      0.67     42785
     

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


52 0.7554701785057851


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

              precision    recall  f1-score   support

           7       0.85      0.29      0.43     70364
           8       0.52      0.90      0.66    233774
           9       0.29      0.04      0.08     59744
          10       0.91      0.91      0.91     90648
          12       0.85      0.47      0.61     52731
          14       0.80      0.78      0.79     74399
          15       0.50      0.69      0.58    112048
          16       0.70      0.64      0.67    719501
          17       0.96      0.38      0.54     33769
          18       0.96      0.97      0.96    408730
          19       0.61      0.09      0.15    225339
          20       0.70      0.59      0.64      6700
          22       0.82      1.00      0.90    433777
          23       0.52      0.51      0.51     25361
          24       0.62      0.15      0.24     75146
          25       0.57      0.96      0.72     27515
          27       0.99      0.48      0.65     42864
          28       0.78    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


1 0.7631007514278347


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

              precision    recall  f1-score   support

           7       0.84      0.29      0.43     70379
           8       0.52      0.90      0.66    230401
           9       0.78      0.32      0.46     70491
          10       0.92      0.92      0.92     90415
          12       0.86      0.48      0.61     51956
          14       0.80      0.80      0.80     74141
          15       0.47      0.69      0.56    111869
          16       0.67      0.65      0.66    717339
          17       0.95      0.39      0.55     34639
          18       0.96      0.97      0.96    408218
          19       0.59      0.09      0.16    223549
          20       0.72      0.58      0.64      7071
          22       0.88      1.00      0.94    596785
          23       0.52      0.53      0.52     24271
          24       0.52      0.12      0.19     72138
          25       0.58      0.96      0.73     27807
          27       0.99      0.48      0.64     41440
          28       0.78    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


2 0.7242166704046916


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

              precision    recall  f1-score   support

           7       0.88      0.29      0.44     70198
           8       0.16      0.86      0.28     45366
           9       0.07      0.02      0.03     12587
          10       0.93      0.92      0.93     83357
          12       0.86      0.47      0.61     49881
          14       0.80      0.80      0.80     72818
          15       0.50      0.70      0.58    109373
          16       0.63      0.49      0.55    724282
          17       0.67      0.39      0.49      7572
          18       0.97      0.97      0.97    409331
          19       0.67      0.04      0.08    215858
          20       0.65      0.59      0.62      7003
          22       0.90      1.00      0.95    535039
          23       0.34      0.12      0.17     41581
          24       0.23      0.11      0.15     15031
          25       0.23      0.96      0.37      6400
          27       0.99      0.52      0.68     43962
          28       0.69    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


3 0.6780905817309657
              precision    recall  f1-score   support

           7       0.90      0.29      0.44     63386
           8       0.47      0.91      0.62    178544
           9       0.92      0.42      0.58     60345
          10       0.94      0.86      0.90     49967
          12       0.84      0.45      0.58     44468
          14       0.77      0.81      0.79     60771
          15       0.44      0.68      0.54     93536
          16       0.57      0.57      0.57    653048
          17       0.89      0.49      0.63     21947
          18       0.97      0.97      0.97    368598
          19       0.47      0.03      0.06    200964
          20       0.81      0.50      0.61      7962
          22       0.31      0.66      0.42     41128
          23       0.28      0.33      0.30     14082
          24       0.47      0.13      0.20     57233
          25       0.55      0.96      0.70     22444
          27       0.97      0.46      0.62     35782
      

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


4 0.6826693964722959


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

              precision    recall  f1-score   support

           7       0.88      0.29      0.44     62563
           8       0.49      0.93      0.65    196288
           9       0.33      0.23      0.27     59222
          10       0.97      0.82      0.89     70757
          12       0.84      0.44      0.57     43098
          14       0.73      0.81      0.77     58946
          15       0.43      0.67      0.52     94104
          16       0.53      0.45      0.48    655650
          17       0.83      0.48      0.61     22568
          18       0.97      0.97      0.97    364977
          19       0.43      0.02      0.04    199679
          20       0.85      0.54      0.66      6721
          22       0.83      0.99      0.91    407463
          23       0.15      0.04      0.06     50531
          24       0.49      0.10      0.16     65599
          25       0.43      0.77      0.55     24536
          27       0.97      0.44      0.61     34370
          28       0.66    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


5 0.7005767262870469


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

              precision    recall  f1-score   support

           7       0.83      0.29      0.43     70311
           8       0.51      0.93      0.66    226493
           9       0.65      0.33      0.44     71633
          10       0.92      0.86      0.89     99662
          12       0.83      0.39      0.53     48459
          14       0.76      0.79      0.78     72425
          15       0.44      0.67      0.53    107501
          16       0.56      0.47      0.51    769799
          17       0.84      0.49      0.62     24922
          18       0.96      0.97      0.97    412279
          19       0.61      0.04      0.07    219454
          20       0.61      0.53      0.57      7473
          22       0.85      0.99      0.91    582582
          23       0.36      0.12      0.17     62764
          24       0.59      0.21      0.31     83340
          25       0.44      0.75      0.56     27630
          27       0.97      0.42      0.59     37707
          28       0.66    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


6 0.7110765939013037


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

              precision    recall  f1-score   support

           7       0.84      0.29      0.43     69985
           8       0.50      0.93      0.65    222672
           9       0.40      0.21      0.28     67952
          10       0.89      0.89      0.89     71466
          12       0.80      0.32      0.45     49483
          14       0.82      0.81      0.81     69465
          15       0.40      0.68      0.50     81676
          16       0.50      0.53      0.52    459253
          17       0.89      0.49      0.63     24156
          18       0.97      0.97      0.97    410825
          19       0.54      0.03      0.06    224250
          20       0.61      0.55      0.58      7318
          22       0.86      1.00      0.92    542587
          23       0.46      0.20      0.27     59528
          24       0.64      0.27      0.38     90574
          25       0.54      0.95      0.69     26398
          27       0.98      0.42      0.59     37877
          28       0.70    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


7 0.712656351446845


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

              precision    recall  f1-score   support

           7       0.83      0.29      0.43     70226
           8       0.51      0.93      0.66    225520
           9       0.30      0.15      0.20     68416
          10       0.88      0.84      0.86     75191
          12       0.78      0.27      0.40     51810
          14       0.88      0.78      0.83     73304
          15       0.28      0.76      0.40     39271
          16       0.00      0.00      0.00         0
          17       0.94      0.49      0.64     24035
          18       0.98      0.97      0.98    411803
          19       0.59      0.03      0.07    219862
          20       0.61      0.58      0.59      6627
          22       0.87      1.00      0.93    488089
          23       0.48      0.20      0.28     59630
          24       0.66      0.25      0.37     88859
          25       0.55      0.96      0.70     26434
          27       0.99      0.47      0.64     40052
          28       0.00    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


8 0.7029120006057248
              precision    recall  f1-score   support

           7       0.81      0.29      0.43     70345
           8       0.50      0.92      0.65    222122
           9       0.04      0.02      0.03     35679
          10       0.86      0.88      0.87     82769
          12       0.77      0.32      0.45     54906
          14       0.81      0.77      0.79     74216
          15       0.38      0.69      0.49     67592
          16       0.38      0.41      0.39    281797
          17       0.88      0.46      0.61     25830
          18       0.98      0.97      0.97    411608
          19       0.48      0.03      0.06    221747
          20       0.63      0.56      0.59      6901
          22       0.87      1.00      0.93    513784
          23       0.43      0.22      0.29     41180
          24       0.65      0.22      0.33     87088
          25       0.56      0.96      0.70     26738
          27       0.94      0.47      0.63     41168
      

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


9 0.7270034156931984


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

              precision    recall  f1-score   support

           7       0.88      0.29      0.44     62496
           8       0.35      0.91      0.51    107452
           9       0.00      0.00      0.00         0
          10       0.96      0.93      0.94     78953
          12       0.84      0.42      0.56     48087
          14       0.00      0.00      0.00         0
          15       0.49      0.66      0.57     92488
          16       0.58      0.57      0.57    555279
          17       0.89      0.52      0.66     22665
          18       0.97      0.97      0.97    364013
          19       0.66      0.04      0.07    196770
          20       0.74      0.58      0.65      5606
          22       0.90      1.00      0.94    531023
          23       0.30      0.33      0.32     13862
          24       0.79      0.31      0.44     84770
          25       0.60      0.95      0.74     25683
          27       0.94      0.47      0.63     35713
          28       0.71    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


10 0.6829672065392397


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           7       0.85      0.32      0.47     55031
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.81      0.80      0.80     60072
          12       0.23      0.53      0.32     41194
          14       0.75      0.65      0.70     55736
          15       0.33      0.53      0.40     66424
          16       0.50      0.73      0.59    407018
          17       0.62      0.30      0.41     20358
          18       0.96      0.97      0.97    354232
          19       1.00      0.95      0.97    191909
          20       0.45      0.23      0.30      5259
          22       0.44      0.88      0.59     53581
          23       0.58      0.19      0.29     91973
          24       0.67      0.39      0.49     91911
          25       0.56      0.96      0.71     25017
          27       0.99      0.52      0.68     30975
          28       0.87    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


11 0.6862548994097804


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           7       0.86      0.29      0.44     68400
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.79      0.79      0.79     63027
          12       0.22      0.55      0.31     43952
          14       0.74      0.65      0.69     63647
          15       0.34      0.53      0.42     75692
          16       0.53      0.70      0.61    514403
          17       0.66      0.32      0.43     23516
          18       0.96      0.97      0.97    399829
          19       1.00      0.95      0.97    215803
          20       0.59      0.23      0.33      5782
          22       0.49      1.00      0.66     61958
          23       0.43      0.21      0.28     46288
          24       0.66      0.26      0.37     87341
          25       0.63      0.96      0.76     25901
          27       0.97      0.55      0.70     33004
          28       0.83    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


12 0.707485309565554


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           7       0.82      0.29      0.43     70174
           8       0.00      0.00      0.00         0
           9       0.53      0.43      0.48     47594
          10       0.58      0.91      0.71     26363
          12       0.17      0.53      0.26     13495
          14       0.80      0.71      0.75     70610
          15       0.19      0.47      0.27     45894
          16       0.61      0.73      0.67    613142
          17       0.68      0.32      0.44     23722
          18       0.97      0.97      0.97    409069
          19       1.00      0.93      0.96    223463
          20       0.80      0.23      0.36      6018
          21       0.00      0.00      0.00       362
          22       0.23      1.00      0.38     22686
          23       0.17      0.12      0.14     21111
          24       0.81      0.24      0.37     90967
          25       0.60      0.96      0.74     27370
          27       0.95    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


13 0.6836834830876141


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           7       0.80      0.29      0.43     69558
           8       0.00      0.00      0.00         0
           9       0.50      0.26      0.34     68216
          10       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          14       0.80      0.69      0.74     71459
          15       0.10      0.36      0.16     27343
          16       0.58      0.64      0.61    623252
          17       0.68      0.32      0.44     23022
          18       0.97      0.97      0.97    405880
          19       1.00      0.94      0.97    219673
          20       0.83      0.23      0.36      5799
          22       0.00      0.00      0.00         0
          23       0.29      0.35      0.32     14990
          24       0.81      0.28      0.42     93158
          25       0.61      0.96      0.74     28072
          27       0.95      0.46      0.62     37179
          28       0.72    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


14 0.6918678092165242


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           7       0.80      0.29      0.43     69877
           8       0.00      0.00      0.00         0
           9       0.54      0.37      0.44     72466
          10       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          14       0.82      0.65      0.73     72646
          15       0.09      0.35      0.15     24796
          16       0.48      0.65      0.55    332153
          17       0.75      0.32      0.45     23026
          18       0.98      0.97      0.97    409857
          19       1.00      0.93      0.97    222734
          20       0.62      0.23      0.33      5941
          22       0.00      0.00      0.00         0
          23       0.50      0.22      0.30     52459
          24       0.68      0.24      0.35     84321
          25       0.57      0.96      0.71     26362
          27       0.94      0.44      0.60     30924
          28       0.80    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


15 0.6784450068904642


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           7       0.79      0.29      0.43     70150
           8       0.00      0.00      0.00         0
           9       0.38      0.23      0.29     66483
          10       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          14       0.80      0.65      0.72     74017
          15       0.08      0.33      0.12     23283
          16       0.49      0.77      0.59    285257
          17       0.82      0.31      0.45     23823
          18       0.98      0.97      0.97    408100
          19       1.00      0.94      0.97    220792
          20       0.43      0.01      0.01     90530
          22       0.00      0.00      0.00         0
          23       0.49      0.23      0.31     52507
          24       0.68      0.24      0.36     85571
          25       0.55      0.96      0.70     25852
          27       0.96      0.50      0.66     40813
          28       0.89    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


16 0.6476005258300777


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           7       0.79      0.29      0.43     69486
           8       0.00      0.00      0.00         0
           9       0.59      0.47      0.53     77220
          10       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          14       0.81      0.67      0.73     73652
          15       0.06      0.31      0.10     20004
          16       0.07      0.80      0.14     19803
          17       0.91      0.34      0.49     24627
          18       0.99      0.97      0.98    407296
          19       1.00      0.95      0.97    219736
          20       0.03      0.00      0.00    146306
          22       0.00      0.00      0.00         0
          23       0.51      0.23      0.32     51530
          24       0.53      0.15      0.23     76302
          25       0.55      0.96      0.70     24562
          27       0.96      0.50      0.65     40018
          28       0.98    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


17 0.6363752677341229


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           7       0.62      0.29      0.40     24604
           8       0.00      0.00      0.00         0
           9       0.31      0.16      0.21     64662
          10       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          14       0.78      0.64      0.70     67195
          15       0.07      0.29      0.12     18700
          16       0.05      0.81      0.10     14281
          17       0.78      0.34      0.48     23117
          18       0.99      0.97      0.98    403245
          19       1.00      0.94      0.97    220232
          20       0.02      0.00      0.00    145608
          22       0.00      0.00      0.00         0
          23       0.52      0.23      0.32     51621
          24       0.55      0.15      0.23     74235
          25       0.56      0.95      0.71     25054
          27       0.95      0.45      0.61     35077
          28       0.98    

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
advClassifier = ScikitlearnDecisionTreeClassifier(model=dtc)
dtAdv = DecisionTreeAttack(classifier=advClassifier)

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/deprecation.py:103: FutureWarning: The attribute `n_features_` is deprecated in 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)


In [22]:
for date in testCons:
    testCon = df['time'].dt.isocalendar().week == pd.Timestamp(date).week
    #testCon = df['time'].dt.date == pd.Timestamp(date).date
    testDF = df[testCon]

    X = testDF[XCols]
    y = testDF[label]
    
    if len(X) == 0: 
        continue
    x_test_adv = dtAdv.generate(x=X.values)
   
    np.savetxt(f"dtAdv-{date.week}.csv", x_test_adv, delimiter=",")

   # Step 7: Evaluate the ART classifier on adversarial test examples
    y_dtc = advClassifier.predict(x_test_adv)
    print("DT test")
    print(f"{date.week}", metrics.f1_score(y, np.rint(y_dtc).argmax(axis=1), average='micro'))
    print(classification_report(y, np.rint(y_dtc).argmax(axis=1)))#, labels=devs))
  

Decision tree attack: 100%|██████████| 473091/473091 [03:27<00:00, 2281.14it/s]


DT test
44 0.0


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       0.0
           7       0.00      0.00      0.00    6745.0
           8       0.00      0.00      0.00   36559.0
           9       0.00      0.00      0.00    9418.0
          10       0.00      0.00      0.00   12953.0
          12       0.00      0.00      0.00    7509.0
          13       0.00      0.00      0.00       0.0
          14       0.00      0.00      0.00   11626.0
          15       0.00      0.00      0.00   23081.0
          16       0.00      0.00      0.00   66903.0
          17       0.00      0.00      0.00       0.0
          18       0.00      0.00      0.00   66743.0
          19       0.00      0.00      0.00   36295.0
          20       0.00      0.00      0.00     944.0
          22       0.00      0.00      0.00   81312.0
          23       0.00      0.00      0.00    4289.0
          24       0.00    

Decision tree attack: 100%|██████████| 2483988/2483988 [19:17<00:00, 2145.78it/s]


DT test
45 1.2077353030690969e-06


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           7       0.00      0.00      0.00    142115
           8       0.00      0.00      0.00    144668
           9       0.00      0.00      0.00     45241
          10       0.00      0.00      0.00     52818
          12       0.00      0.00      0.00    148710
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00     43272
          15       0.00      0.00      0.00    109634
          16       0.00      0.00      0.00    248788
          17       0.00      0.00      0.00     14544
          18       0.00      0.00      0.00    257285
          19       0.00      0.00      0.00    146426
          20       0.00      0.00      0.00      4327
          22       0.00      0.00      0.00    212008
          23       0.00    

Decision tree attack: 100%|██████████| 2372820/2372820 [16:59<00:00, 2327.74it/s]


DT test
46 1.2643184059473537e-06


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           7       0.00      0.00      0.00     23908
           8       0.00      0.00      0.00    133305
           9       0.00      0.00      0.00     43781
          10       0.00      0.00      0.00     43927
          12       0.00      0.00      0.00     30254
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00     43880
          15       0.00      0.00      0.00     66008
          16       0.00      0.00      0.00    447899
          17       0.00      0.00      0.00     15588
          18       0.00      0.00      0.00    234606
          19       0.00      0.00      0.00    133445
          20       0.00      0.00      0.00      3692
          22       0.00      0.00      0.00    345014
          23       0.00      0.00      0.00      9006
          24       0.00    

Decision tree attack: 100%|██████████| 2267160/2267160 [16:13<00:00, 2329.10it/s]


DT test
47 1.7643218828843134e-06


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           7       0.00      0.00      0.00     23434
           8       0.00      0.00      0.00    125743
           9       0.00      0.00      0.00     44372
          10       0.00      0.00      0.00     47172
          12       0.00      0.00      0.00     26405
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00     41118
          15       0.00      0.00      0.00     65078
          16       0.00      0.00      0.00    412871
          17       0.00      0.00      0.00     16085
          18       0.00      0.00      0.00    222083
          19       0.00      0.00      0.00    124628
          20       0.00      0.00      0.00      3868
          22       0.00      0.00      0.00    336185
          23       0.00      0.00      0.00     51609
          24       0.00    

Decision tree attack: 100%|██████████| 3502328/3502328 [24:48<00:00, 2352.98it/s]


DT test
48 2.855243712182297e-07


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           7       0.00      0.00      0.00     37178
           8       0.00      0.00      0.00    199285
           9       0.00      0.00      0.00     63841
          10       0.00      0.00      0.00     55480
          12       0.00      0.00      0.00     47948
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00     57633
          15       0.00      0.00      0.00    104629
          16       0.00      0.00      0.00    633618
          17       0.00      0.00      0.00     21328
          18       0.00      0.00      0.00    366565
          19       0.00      0.00      0.00    199374
          20       0.00      0.00      0.00      5790
          22       0.00      0.00      0.00    459505
          23       0.00      0.00      0.00     22620
          24       0.00    

Decision tree attack: 100%|██████████| 3965858/3965858 [28:06<00:00, 2352.16it/s]


DT test
49 0.0


/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       0.0
           7       0.00      0.00      0.00   41723.0
           8       0.00      0.00      0.00  220605.0
           9       0.00      0.00      0.00   75860.0
          10       0.00      0.00      0.00   69738.0
          12       0.00      0.00      0.00   54084.0
          13       0.00      0.00      0.00       0.0
          14       0.00      0.00      0.00   64200.0
          15       0.00      0.00      0.00  115643.0
          16       0.00      0.00      0.00  717815.0
          17       0.00      0.00      0.00   24382.0
          18       0.00      0.00      0.00  404703.0
          19       0.00      0.00      0.00  220202.0
          20       0.00      0.00      0.00    6236.0
          22       0.00      0.00      0.00  597306.0
          23       0.00      0.00      0.00   24102.0
          24       0.00    

Decision tree attack:  14%|█▍        | 550596/3891198 [03:54<23:42, 2347.74it/s]


KeyboardInterrupt: 

In [21]:
print(multilabel_confusion_matrix(y, np.rint(y_dtc).argmax(axis=1)))

[[[361443. 111648.]
  [     0.      0.]]

 [[195288. 277803.]
  [     0.      0.]]

 [[414958.  51388.]
  [  6745.      0.]]

 [[436532.      0.]
  [ 36559.      0.]]

 [[460280.   3393.]
  [  9418.      0.]]

 [[460138.      0.]
  [ 12953.      0.]]

 [[465582.      0.]
  [  7509.      0.]]

 [[456485.  16606.]
  [     0.      0.]]

 [[461465.      0.]
  [ 11626.      0.]]

 [[450010.      0.]
  [ 23081.      0.]]

 [[406188.      0.]
  [ 66903.      0.]]

 [[460838.  12253.]
  [     0.      0.]]

 [[406348.      0.]
  [ 66743.      0.]]

 [[436796.      0.]
  [ 36295.      0.]]

 [[472147.      0.]
  [   944.      0.]]

 [[391779.      0.]
  [ 81312.      0.]]

 [[468802.      0.]
  [  4289.      0.]]

 [[461097.      0.]
  [ 11994.      0.]]

 [[456618.      0.]
  [ 16473.      0.]]

 [[467723.      0.]
  [  5368.      0.]]

 [[443724.      0.]
  [ 29367.      0.]]

 [[468093.      0.]
  [  4998.      0.]]

 [[461974.      0.]
  [ 11117.      0.]]

 [[451614.      0.]
  [ 21477.    

In [8]:
from art.metrics import RobustnessVerificationTreeModelsCliqueMethod
aclassifier = SklearnClassifier(model=dtc)
rt = RobustnessVerificationTreeModelsCliqueMethod(classifier=aclassifier)
average_bound, verified_error = rt.verify(x=X_test, y=y_test, eps_init=0.3, nb_search_steps=10, max_clique=2, 
                                          max_level=2)

print('Average bound:', average_bound)
print('Verified error at eps:', verified_error)

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/deprecation.py:103: FutureWarning: The attribute `n_features_` is deprecated in 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)


AttributeError: 'ScikitlearnDecisionTreeClassifier' object has no attribute 'get_trees'

In [8]:
advClassifier = SklearnClassifier(dtc)
zoo = DecisionTreeAttack(classifier=advClassifier)

/rds/general/user/as9820/home/anaconda3/envs/test1/lib/python3.9/site-packages/sklearn/utils/deprecation.py:103: FutureWarning: The attribute `n_features_` is deprecated in 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)


In [15]:
dist = 0
for date in testCons:
    path = Path(f"dt1sec_0adv-{date.week}.csv")
    if path.is_file():
        print("test exists")
        x_test_adv = np.loadtxt(f"dt1sec_0adv-{date.week}.csv", delimiter=",", dtype=str)
    testCon = df['time'].dt.isocalendar().week == pd.Timestamp(date).week
    #testCon = df['time'].dt.date == pd.Timestamp(date).date
    testDF = df[testCon]

    X = testDF[XCols]
    y = testDF[label]
    
    #X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=200, stratify=y)
    
    if len(X) == 0: 
        continue
    #x_test_adv = zoo.generate(x=X_test.values, y=y_test-2)
   
    #np.savetxt(f"RFzoo2-{date.week}.csv", x_test_adv, delimiter=",")

   # Step 7: Evaluate the ART classifier on adversarial test examples
    #y_rfc = advClassifier.predict(x_test_adv)
    for index, sample in enumerate (x_test_adv):
        dist = dist + np.linalg.norm(sample-X[index])
    print(dist)
    #print(dtc.score(x_test_adv, y_test))
    #print(f"{date.week}", metrics.f1_score(y, y_rfc, average='micro'))

test exists


KeyError: 0

In [ ]:
advClassifier = ScikitlearnDecisionTreeClassifier(model=dtc)
dtAdv = Zero(classifier=advClassifier)